on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Run `yarn upgrade`
    - uses: browniebroke/yarn-upgrade-action@v1

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        branch: update/yarn-upgrade
        title: Run yarn upgrade
        commit-message: "Run yarn upgrade"